{'stack': {'backgrounds': [{'components': [{'name': 'Frame1',
                                            'position': (8, 8),
                                            'size': (617, 217),
                                            'type': 'StaticBox'},
                                           {'name': 'Label1',
                                            'position': (24, 32),
                                            'text': 'Enter your string here',
                                            'type': 'StaticText'},
                                           {'name': 'Label2',
                                            'position': (40, 64),
                                            'text': 'Lower case',
                                            'type': 'StaticText'},
                                           {'name': 'Label3',
                                            'position': (40, 88),
                                            'text': 'Reversed',
                                            'type': 'StaticText'},
                                           {'name': 'Label4',
                                            'position': (40, 120),
                                            'text': 'Split into words',
                                            'type': 'StaticText'},
                                           {'items': [],
                                            'name': 'lstSplit',
                                            'position': (144, 120),
                                            'size': (441, 82),
                                            'type': 'List'},
                                           {'name': 'txtLower',
                                            'position': (144, 56),
                                            'size': (441, 25),
                                            'text': 'Text1',
                                            'type': 'TextField'},
                                           {'name': 'txtRawString',
                                            'position': (144, 24),
                                            'size': (441, 27),
                                            'text': 'This TEXT contains a few words',
                                            'type': 'TextField'},
                                           {'name': 'txtReverse',
                                            'position': (144, 88),
                                            'size': (441, 25),
                                            'text': 'Text1',
                                            'type': 'TextField'},
                                           {'name': 'Frame2',
                                            'position': (8, 264),
                                            'size': (617, 81),
                                            'type': 'StaticBox'},
                                           {'name': 'Label5',
                                            'position': (24, 296),
                                            'text': 'Number',
                                            'type': 'StaticText'},
                                           {'items': ['Sin',
                                                      'Cos',
                                                      'Factorial',
                                                      'Sqrt'],
                                            'name': 'cmbFunction',
                                            'position': (240, 296),
                                            'size': (193, 21),
                                            'type': 'ComboBox'},
                                           {'name': 'lblResult',
                                            'position': (448, 296),
                                            'text': 'Answer',
                                            'type': 'StaticText'},
                                           {'name': 'txtValue',
                                            'position': (72, 296),
                                            'size': (153, 25),
                                            'text': '1',
                                            'type': 'TextField'},
                                           {'name': 'Frame3',
                                            'position': (8, 352),
                                            'size': (617, 169),
                                            'type': 'StaticBox'},
                                           {'name': 'Label6',
                                            'position': (24, 416),
                                            'text': 'Cell',
                                            'type': 'StaticText'},
                                           {'label': 'Attach to Excel',
                                            'name': 'cmdAttach',
                                            'position': (24, 376),
                                            'size': (129, 25),
                                            'type': 'Button'},
                                           {'label': 'Get Value',
                                            'name': 'cmdGetValue',
                                            'position': (128, 416),
                                            'size': (89, 25),
                                            'type': 'Button'},
                                           {'label': 'Set Value',
                                            'name': 'cmdSetValue',
                                            'position': (128, 448),
                                            'size': (89, 25),
                                            'type': 'Button'},
                                           {'name': 'lblAttached',
                                            'position': (168, 376),
                                            'text': 'Not attached',
                                            'type': 'StaticText'},
                                           {'name': 'lblCellValue',
                                            'position': (232, 416),
                                            'text': '=',
                                            'type': 'StaticText'},
                                           {'name': 'txtCell',
                                            'position': (56, 416),
                                            'size': (49, 25),
                                            'text': 'A1',
                                            'type': 'TextField'},
                                           {'name': 'txtNewValue',
                                            'position': (56, 448),
                                            'size': (49, 25),
                                            'text': '',
                                            'type': 'TextField'},
                                           {'name': 'Frame4',
                                            'position': (8, 528),
                                            'size': (617, 49),
                                            'type': 'StaticBox'},
                                           {'label': 'Get User Name',
                                            'name': 'cmdGetUserName',
                                            'position': (24, 544),
                                            'size': (121, 25),
                                            'type': 'Button'},
                                           {'name': 'lblUserName',
                                            'position': (160, 544),
                                            'text': 'Press the button to check',
                                            'type': 'StaticText'},
                                           {'label': 'Clear Text',
                                            'name': 'cmdClear',
                                            'position': (416, 232),
                                            'size': (105, 25),
                                            'type': 'Button'},
                                           {'label': 'Close',
                                            'name': 'cmdClose',
                                            'position': (528, 232),
                                            'size': (97, 25),
                                            'type': 'Button'},
                                           {'label': 'Default',
                                            'name': 'cmdDefault',
                                            'position': (8, 232),
                                            'size': (97, 25),
                                            'type': 'Button'},
                                           {'label': 'Process Text',
                                            'name': 'cmdDoIt',
                                            'position': (304, 232),
                                            'size': (105, 25),
                                            'type': 'Button'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmMain',
                            'position': (4, 30),
                            'size': (632, 604),
                            'style': ['resizeable'],
                            'title': 'vb2py Test Form',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
