{'application': {'backgrounds': [{'components': [{'name': 'Frame1',
                                                  'position': (8, 8),
                                                  'size': (617, 217),
                                                  'type': 'StaticBox'},
                                                 {'name': 'Label1',
                                                  'position': (24, 32),
                                                  'text': 'Enter your string here',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'Label2',
                                                  'position': (40, 64),
                                                  'text': 'Lower case',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'Label3',
                                                  'position': (40, 88),
                                                  'text': 'Reversed',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'Label4',
                                                  'position': (40, 120),
                                                  'text': 'Split into words',
                                                  'type': 'VBStaticText'},
                                                 {'items': [],
                                                  'name': 'lstSplit',
                                                  'position': (144, 120),
                                                  'size': (441, 82),
                                                  'type': 'VBList'},
                                                 {'name': 'txtLower',
                                                  'position': (144, 56),
                                                  'size': (441, 25),
                                                  'text': 'Text1',
                                                  'type': 'VBTextField'},
                                                 {'name': 'txtRawString',
                                                  'position': (144, 24),
                                                  'size': (441, 27),
                                                  'text': 'This TEXT contains a few words',
                                                  'type': 'VBTextField'},
                                                 {'name': 'txtReverse',
                                                  'position': (144, 88),
                                                  'size': (441, 25),
                                                  'text': 'Text1',
                                                  'type': 'VBTextField'},
                                                 {'name': 'Frame2',
                                                  'position': (8, 264),
                                                  'size': (617, 81),
                                                  'type': 'StaticBox'},
                                                 {'name': 'Label5',
                                                  'position': (24, 296),
                                                  'text': 'Number',
                                                  'type': 'VBStaticText'},
                                                 {'items': ['Sin',
                                                            'Cos',
                                                            'Factorial',
                                                            'Sqrt'],
                                                  'name': 'cmbFunction',
                                                  'position': (240, 296),
                                                  'size': (193, 21),
                                                  'type': 'VBComboBox'},
                                                 {'name': 'lblResult',
                                                  'position': (448, 296),
                                                  'text': 'Answer',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'txtValue',
                                                  'position': (72, 296),
                                                  'size': (153, 25),
                                                  'text': '1',
                                                  'type': 'VBTextField'},
                                                 {'name': 'Frame3',
                                                  'position': (8, 352),
                                                  'size': (617, 169),
                                                  'type': 'StaticBox'},
                                                 {'name': 'Label6',
                                                  'position': (24, 416),
                                                  'text': 'Cell',
                                                  'type': 'VBStaticText'},
                                                 {'label': 'Attach to Excel',
                                                  'name': 'cmdAttach',
                                                  'position': (24, 376),
                                                  'size': (129, 25),
                                                  'type': 'VBButton'},
                                                 {'label': 'Get Value',
                                                  'name': 'cmdGetValue',
                                                  'position': (128, 416),
                                                  'size': (89, 25),
                                                  'type': 'VBButton'},
                                                 {'label': 'Set Value',
                                                  'name': 'cmdSetValue',
                                                  'position': (128, 448),
                                                  'size': (89, 25),
                                                  'type': 'VBButton'},
                                                 {'name': 'lblAttached',
                                                  'position': (168, 376),
                                                  'text': 'Not attached',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'lblCellValue',
                                                  'position': (232, 416),
                                                  'text': '=',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'txtCell',
                                                  'position': (56, 416),
                                                  'size': (49, 25),
                                                  'text': 'A1',
                                                  'type': 'VBTextField'},
                                                 {'name': 'txtNewValue',
                                                  'position': (56, 448),
                                                  'size': (49, 25),
                                                  'text': '',
                                                  'type': 'VBTextField'},
                                                 {'name': 'Frame4',
                                                  'position': (8, 528),
                                                  'size': (617, 49),
                                                  'type': 'StaticBox'},
                                                 {'label': 'Get User Name',
                                                  'name': 'cmdGetUserName',
                                                  'position': (24, 544),
                                                  'size': (121, 25),
                                                  'type': 'VBButton'},
                                                 {'name': 'lblUserName',
                                                  'position': (160, 544),
                                                  'text': 'Press the button to check',
                                                  'type': 'VBStaticText'},
                                                 {'label': 'Clear Text',
                                                  'name': 'cmdClear',
                                                  'position': (416, 232),
                                                  'size': (105, 25),
                                                  'type': 'VBButton'},
                                                 {'label': 'Close',
                                                  'name': 'cmdClose',
                                                  'position': (528, 232),
                                                  'size': (97, 25),
                                                  'type': 'VBButton'},
                                                 {'label': 'Default',
                                                  'name': 'cmdDefault',
                                                  'position': (8, 232),
                                                  'size': (97, 25),
                                                  'type': 'VBButton'},
                                                 {'label': 'Process Text',
                                                  'name': 'cmdDoIt',
                                                  'position': (304, 232),
                                                  'size': (105, 25),
                                                  'type': 'VBButton'}],
                                  'menubar': {'menus': [],
                                              'type': 'MenuBar'},
                                  'name': 'frmMain',
                                  'position': (4, 30),
                                  'size': (632, 604),
                                  'style': ['resizeable'],
                                  'title': 'vb2py Test Form',
                                  'type': 'Background'}],
                 'name': 'Template',
                 'type': 'Application'}}
