{'stack': {'backgrounds': [{'components': [{'label': 'Start timer',
                                            'name': 'Command1',
                                            'position': (48, 152),
                                            'size': (97, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Load form 2',
                                            'name': 'Command2',
                                            'position': (152, 152),
                                            'size': (73, 33),
                                            'type': 'VBButton'},
                                           {'name': 'Text2',
                                            'position': (48, 64),
                                            'size': (97, 25),
                                            'text': 'Text2',
                                            'type': 'VBTextField'},
                                           {'name': 'Text3',
                                            'position': (48, 104),
                                            'size': (97, 25),
                                            'text': 'Text2',
                                            'type': 'VBTextField'},
                                           {'name': 'Timer1',
                                            'position': (48, 208),
                                            'type': 'VBTimer'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'Form1',
                            'position': (4, 30),
                            'size': (240, 292),
                            'style': ['resizeable'],
                            'title': 'Form1',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
