{'stack': {'backgrounds': [{'components': [{'name': 'Frame1',
                                            'position': (8, 8),
                                            'size': (329, 433),
                                            'type': 'StaticBox'},
                                           {'label': 'From file ...',
                                            'name': 'cmdFromFile',
                                            'position': (248, 408),
                                            'size': (81, 25),
                                            'type': 'Button'},
                                           {'name': 'txtVB',
                                            'position': (16, 24),
                                            'size': (313, 377),
                                            'text': '',
                                            'type': 'TextField'},
                                           {'name': 'Frame2',
                                            'position': (344, 8),
                                            'size': (329, 433),
                                            'type': 'StaticBox'},
                                           {'name': 'Text1',
                                            'position': (352, 24),
                                            'size': (313, 377),
                                            'text': '',
                                            'type': 'TextField'},
                                           {'label': 'To file ...',
                                            'name': 'cmdToFile',
                                            'position': (584, 408),
                                            'size': (81, 25),
                                            'type': 'Button'}],
                            'menubar': {'menus': [{'items': [{'label': '&Copy',
                                                              'name': 'mnuCopy',
                                                              'type': 'MenuItem'},
                                                             {'label': '&Paste',
                                                              'name': 'mnuPaste',
                                                              'type': 'MenuItem'},
                                                             {'label': 'Proper&ties',
                                                              'name': 'mnuProperties',
                                                              'type': 'MenuItem'},
                                                             {'label': '-',
                                                              'name': 'mnuSep1',
                                                              'type': 'MenuItem'}],
                                                   'label': '&Edit',
                                                   'name': 'mnuEdit',
                                                   'type': 'Menu'},
                                                  {'items': [{'label': 'E&xit',
                                                              'name': 'mnuExit',
                                                              'type': 'MenuItem'},
                                                             {'label': '&Open',
                                                              'name': 'mnuOpen',
                                                              'type': 'MenuItem'},
                                                             {'label': '&Save',
                                                              'name': 'mnuSave',
                                                              'type': 'MenuItem'},
                                                             {'label': '-',
                                                              'name': 'mnuSep0',
                                                              'type': 'MenuItem'}],
                                                   'label': '&File',
                                                   'name': 'mnuFile',
                                                   'type': 'Menu'},
                                                  {'items': [{'label': '&About',
                                                              'name': 'mnuAbout',
                                                              'type': 'MenuItem'},
                                                             {'label': '&Help',
                                                              'name': 'mnuShowHelp',
                                                              'type': 'MenuItem'}],
                                                   'label': '&Help',
                                                   'name': 'mnuHelp',
                                                   'type': 'Menu'}],
                                        'type': 'MenuBar'},
                            'name': 'frmMain',
                            'position': (11, 57),
                            'size': (683, 491),
                            'style': ['resizeable'],
                            'title': 'Converter',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
