{'application': {'backgrounds': [{'components': [{'backgroundColor': (192,
                                                                      0,
                                                                      0),
                                                  'foregroundColor': (255,
                                                                      255,
                                                                      255),
                                                  'items': ['you',
                                                            'should',
                                                            'see',
                                                            'this',
                                                            'ok'],
                                                  'name': 'Combo1',
                                                  'position': (56, 136),
                                                  'size': (129, 21),
                                                  'toolTip': 'So should this',
                                                  'type': 'VBComboBox'},
                                                 {'backgroundColor': (0,
                                                                      0,
                                                                      255),
                                                  'label': 'Command1',
                                                  'name': 'Command1',
                                                  'position': (48, 16),
                                                  'size': (97, 57),
                                                  'toolTip': 'Another tip',
                                                  'type': 'VBButton'},
                                                 {'backgroundColor': (0,
                                                                      192,
                                                                      192),
                                                  'foregroundColor': (255,
                                                                      255,
                                                                      0),
                                                  'name': 'Label1',
                                                  'position': (112, 184),
                                                  'text': 'Can you hear me now?',
                                                  'toolTip': 'Am I tipped?',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'Label2',
                                                  'position': (48, 248),
                                                  'text': 'Should see color + tooltips',
                                                  'type': 'VBStaticText'},
                                                 {'backgroundColor': (192,
                                                                      192,
                                                                      0),
                                                  'foregroundColor': (0,
                                                                      128,
                                                                      255),
                                                  'items': ['some',
                                                            'colors',
                                                            'for',
                                                            'your',
                                                            'eyes'],
                                                  'name': 'List1',
                                                  'position': (232, 24),
                                                  'size': (145, 134),
                                                  'toolTip': 'Do you see the tip',
                                                  'type': 'VBList'},
                                                 {'backgroundColor': (0,
                                                                      0,
                                                                      255),
                                                  'foregroundColor': (255,
                                                                      0,
                                                                      255),
                                                  'name': 'Text1',
                                                  'position': (48, 80),
                                                  'size': (161, 25),
                                                  'text': 'Text1',
                                                  'toolTip': 'This should have a tip',
                                                  'type': 'VBTextField'}],
                                  'menubar': {'menus': [],
                                              'type': 'MenuBar'},
                                  'name': 'frmColors',
                                  'position': (4, 30),
                                  'size': (613, 401),
                                  'style': ['resizeable'],
                                  'title': 'Colorful form',
                                  'type': 'Background'}],
                 'name': 'Template',
                 'type': 'Application'}}
