{'stack': {'backgrounds': [{'components': [{'label': 'Like ?',
                                            'name': 'btnCheckLike',
                                            'position': (96, 104),
                                            'size': (121, 25),
                                            'type': 'VBButton'},
                                           {'name': 'lblLike',
                                            'position': (104, 144),
                                            'text': 'Label',
                                            'type': 'VBStaticText'},
                                           {'name': 'txtOne',
                                            'position': (16, 16),
                                            'size': (273, 25),
                                            'text': 'Text1',
                                            'type': 'VBTextField'},
                                           {'name': 'txtTwo',
                                            'position': (16, 56),
                                            'size': (273, 27),
                                            'text': 'Text2',
                                            'type': 'VBTextField'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmForm',
                            'position': (4, 30),
                            'size': (312, 226),
                            'style': ['resizeable'],
                            'title': 'Form1',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
