{'application': {'backgrounds': [{'components': [{'checked': 0,
                                                  'label': 'Check1',
                                                  'name': 'Check1',
                                                  'position': (224, 224),
                                                  'type': 'VBCheckBox'},
                                                 {'checked': 1,
                                                  'label': 'Check2',
                                                  'name': 'Check2',
                                                  'position': (224, 248),
                                                  'type': 'VBCheckBox'},
                                                 {'items': ['hello',
                                                            'goodbye',
                                                            'see you',
                                                            'back again',
                                                            'here',
                                                            'there',
                                                            'everywhere'],
                                                  'name': 'Combo1',
                                                  'position': (240, 144),
                                                  'size': (169, 21),
                                                  'type': 'VBComboBox'},
                                                 {'items': ['thing'],
                                                  'name': 'Combo2',
                                                  'position': (240, 176),
                                                  'size': (169, 21),
                                                  'type': 'VBComboBox'},
                                                 {'items': [],
                                                  'name': 'Combo3',
                                                  'position': (24, 200),
                                                  'size': (177, 21),
                                                  'type': 'VBComboBox'},
                                                 {'label': 'Show radio',
                                                  'name': 'Command1',
                                                  'position': (464, 288),
                                                  'size': (81, 25),
                                                  'type': 'VBButton'},
                                                 {'name': 'Label1',
                                                  'position': (288, 16),
                                                  'text': 'More static text',
                                                  'type': 'VBStaticText'},
                                                 {'items': ['un',
                                                            'deux',
                                                            'trois',
                                                            'quatre',
                                                            'cinq',
                                                            'six',
                                                            'sept'],
                                                  'name': 'List1',
                                                  'position': (432, 48),
                                                  'size': (233, 95),
                                                  'type': 'VBList'},
                                                 {'items': [],
                                                  'name': 'List2',
                                                  'position': (432, 168),
                                                  'size': (233, 95),
                                                  'type': 'VBList'},
                                                 {'label': 'Change',
                                                  'name': 'btnChange',
                                                  'position': (32, 248),
                                                  'size': (65, 25),
                                                  'type': 'VBButton'},
                                                 {'label': 'Hide me direct',
                                                  'name': 'btnDirectHide',
                                                  'position': (216, 360),
                                                  'size': (81, 25),
                                                  'type': 'VBButton'},
                                                 {'label': 'Do it',
                                                  'name': 'btnDoIt',
                                                  'position': (112, 120),
                                                  'size': (105, 25),
                                                  'type': 'VBButton'},
                                                 {'label': 'Hide me (late bound)',
                                                  'name': 'btnHideMe',
                                                  'position': (288, 320),
                                                  'size': (121, 25),
                                                  'type': 'VBButton'},
                                                 {'label': 'Second Form',
                                                  'name': 'btnSecond',
                                                  'position': (104, 160),
                                                  'size': (113, 25),
                                                  'type': 'VBButton'},
                                                 {'label': 'Zero it!',
                                                  'name': 'btnZeroIt',
                                                  'position': (32, 328),
                                                  'size': (73, 25),
                                                  'type': 'VBButton'},
                                                 {'checked': 1,
                                                  'label': 'Add',
                                                  'name': 'chkAdd',
                                                  'position': (104, 248),
                                                  'type': 'VBCheckBox'},
                                                 {'checked': 0,
                                                  'label': 'Sub',
                                                  'name': 'chkSub',
                                                  'position': (104, 272),
                                                  'type': 'VBCheckBox'},
                                                 {'items': ['one',
                                                            'two',
                                                            'three',
                                                            'four',
                                                            'five'],
                                                  'name': 'cmbChoose',
                                                  'position': (240, 104),
                                                  'size': (177, 21),
                                                  'type': 'VBComboBox'},
                                                 {'label': 'Factorial',
                                                  'name': 'cmdFactorial',
                                                  'position': (568, 352),
                                                  'size': (73, 25),
                                                  'type': 'VBButton'},
                                                 {'name': 'lblLabel',
                                                  'position': (24, 72),
                                                  'text': 'My text',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'txtName',
                                                  'position': (24, 16),
                                                  'size': (113, 25),
                                                  'text': 'Text1',
                                                  'type': 'VBTextField'},
                                                 {'name': 'txtSecond',
                                                  'position': (144, 48),
                                                  'size': (137, 25),
                                                  'text': 'Text1',
                                                  'type': 'VBTextField'},
                                                 {'name': 'txtValue',
                                                  'position': (32, 296),
                                                  'size': (97, 25),
                                                  'text': '0',
                                                  'type': 'VBTextField'}],
                                  'menubar': {'menus': [{'items': [{'label': '&Copy',
                                                                    'name': 'mnuCopy',
                                                                    'type': 'MenuItem'},
                                                                   {'label': 'Paste',
                                                                    'name': 'mnuPaste',
                                                                    'type': 'MenuItem'},
                                                                   {'label': 'Undo',
                                                                    'name': 'mnuUndo',
                                                                    'type': 'MenuItem'}],
                                                         'label': 'Edit',
                                                         'name': 'mnuEdit',
                                                         'type': 'Menu'},
                                                        {'items': [{'label': 'Exit',
                                                                    'name': 'mnuExit',
                                                                    'type': 'MenuItem'},
                                                                   {'label': 'Open',
                                                                    'name': 'mnuOpen',
                                                                    'type': 'MenuItem'},
                                                                   {'label': 'Save',
                                                                    'name': 'mnuSave',
                                                                    'type': 'MenuItem'},
                                                                   {'label': '-',
                                                                    'name': 'mnuSep1',
                                                                    'type': 'MenuItem'}],
                                                         'label': 'File',
                                                         'name': 'mnuFile',
                                                         'type': 'Menu'},
                                                        {'items': [{'label': 'About',
                                                                    'name': 'mnuAbout',
                                                                    'type': 'MenuItem'}],
                                                         'label': 'Help',
                                                         'name': 'mnuHelp',
                                                         'type': 'Menu'}],
                                              'type': 'MenuBar'},
                                  'name': 'frmMain',
                                  'position': (11, 57),
                                  'size': (713, 445),
                                  'style': ['resizeable'],
                                  'title': 'Test form in VB',
                                  'type': 'Background'}],
                 'name': 'Template',
                 'type': 'Application'}}
