{'application': {'backgrounds': [{'components': [{'name': 'File1',
                                                  'position': (152, 96),
                                                  'text': 'Unknown control',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'Label1',
                                                  'position': (24, 8),
                                                  'text': 'C:/Development/Python24/Lib/site-packages/vb2py/vb/test1/frmProblems.frx@48018',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'Label2',
                                                  'position': (328, 72),
                                                  'text': 'Tree view',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'Label3',
                                                  'position': (152, 72),
                                                  'text': 'File list box',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'Label4',
                                                  'position': (24, 136),
                                                  'text': 'Square',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'Label5',
                                                  'position': (152, 168),
                                                  'text': 'OLE Container',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'Label6',
                                                  'position': (152, 240),
                                                  'text': 'List view',
                                                  'type': 'VBStaticText'},
                                                 {'backgroundColor': 'Grey',
                                                  'foregroundColor': 'Grey',
                                                  'name': 'ListView1',
                                                  'position': (152, 264),
                                                  'text': 'Unknown control',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'OLE1',
                                                  'position': (152, 192),
                                                  'text': 'Unknown control',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'Shape1',
                                                  'position': (24, 160),
                                                  'text': 'Unknown control',
                                                  'type': 'VBStaticText'},
                                                 {'name': 'Timer1',
                                                  'position': (32, 80),
                                                  'type': 'VBTimer'},
                                                 {'name': 'TreeView1',
                                                  'position': (328, 96),
                                                  'size': (113, 121),
                                                  'type': 'VBTreeView'}],
                                  'menubar': {'menus': [],
                                              'type': 'MenuBar'},
                                  'name': 'frmProblems',
                                  'position': (4, 30),
                                  'size': (516, 395),
                                  'style': ['resizeable'],
                                  'title': 'Form with problems',
                                  'type': 'Background'}],
                 'name': 'Template',
                 'type': 'Application'}}
