{'stack': {'backgrounds': [{'components': [{'name': 'Frame1',
                                            'position': (208, 24),
                                            'size': (265, 225),
                                            'type': 'StaticBox'},
                                           {'name': 'Frame2',
                                            'position': (232, 120),
                                            'size': (177, 89),
                                            'type': 'StaticBox'},
                                           {'items': ['Real Inner 2',
                                                      'Real Inner 1'],
                                            'name': 'Option7',
                                            'position': (272, 176),
                                            'selected': 'Real Inner 2',
                                            'type': 'RadioGroup'},
                                           {'label': 'Close',
                                            'name': 'btnClose',
                                            'position': (376, 264),
                                            'size': (105, 25),
                                            'type': 'VBButton'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmRadio',
                            'position': (4, 30),
                            'size': (527, 400),
                            'style': ['resizeable'],
                            'title': 'Radio buttons',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
