{'stack': {'backgrounds': [{'components': [{'label': 'Close',
                                            'name': 'btnClose',
                                            'position': (136, 40),
                                            'size': (113, 25),
                                            'type': 'VBButton'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmSecond',
                            'position': (4, 30),
                            'size': (312, 226),
                            'style': ['resizeable'],
                            'title': 'Second Form',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
