{'stack': {'backgrounds': [{'components': [{'label': 'Simple',
                                            'name': 'Command1',
                                            'position': (16, 16),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Cancel',
                                            'name': 'Command10',
                                            'position': (216, 56),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Mimic Mouse Move',
                                            'name': 'Command11',
                                            'position': (320, 56),
                                            'size': (121, 25),
                                            'type': 'VBButton'},
                                           {'backgroundColor': (0,
                                                                128,
                                                                255),
                                            'label': 'Back Colour + Font',
                                            'name': 'Command2',
                                            'position': (112, 16),
                                            'size': (137, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Mouse Cursor',
                                            'name': 'Command3',
                                            'position': (256, 16),
                                            'size': (105, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Make Visible',
                                            'name': 'Command4',
                                            'position': (368, 16),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Move Button',
                                            'name': 'Command5',
                                            'position': (464, 16),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Size Button',
                                            'name': 'Command6',
                                            'position': (560, 16),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Enable',
                                            'name': 'Command7',
                                            'position': (656, 16),
                                            'size': (97, 25),
                                            'type': 'VBButton'},
                                           {'label': 'No Tab Stop',
                                            'name': 'Command8',
                                            'position': (16, 56),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Default',
                                            'name': 'Command9',
                                            'position': (112, 56),
                                            'size': (89, 25),
                                            'type': 'VBButton'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmButton',
                            'position': (4, 30),
                            'size': (785, 128),
                            'style': ['resizeable'],
                            'title': 'Buttons',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
