{'stack': {'backgrounds': [{'components': [{'checked': 0,
                                            'label': 'One',
                                            'name': 'Check1',
                                            'position': (48, 24),
                                            'type': 'VBCheckBox'},
                                           {'checked': 0,
                                            'label': 'Two',
                                            'name': 'Check2',
                                            'position': (48, 56),
                                            'type': 'VBCheckBox'},
                                           {'checked': 0,
                                            'label': 'Three',
                                            'name': 'Check3',
                                            'position': (48, 104),
                                            'type': 'VBCheckBox'},
                                           {'checked': 0,
                                            'label': 'One',
                                            'name': 'Check4',
                                            'position': (232, 16),
                                            'type': 'VBCheckBox'},
                                           {'checked': 0,
                                            'label': 'Two',
                                            'name': 'Check5',
                                            'position': (232, 48),
                                            'type': 'VBCheckBox'},
                                           {'checked': 0,
                                            'label': 'Three',
                                            'name': 'Check6',
                                            'position': (232, 96),
                                            'type': 'VBCheckBox'},
                                           {'label': 'Change Text',
                                            'name': 'Command1',
                                            'position': (408, 24),
                                            'size': (97, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Make Visible',
                                            'name': 'Command4',
                                            'position': (24, 160),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Move ',
                                            'name': 'Command5',
                                            'position': (120, 160),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Size ',
                                            'name': 'Command6',
                                            'position': (216, 160),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Enable',
                                            'name': 'Command7',
                                            'position': (312, 160),
                                            'size': (97, 25),
                                            'type': 'VBButton'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmCheckBox',
                            'position': (4, 30),
                            'size': (614, 315),
                            'style': ['resizeable'],
                            'title': 'Check Boxes',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
