{'stack': {'backgrounds': [{'components': [{'items': ['one', 'two '],
                                            'name': 'Combo1',
                                            'position': (472, 64),
                                            'size': (385, 21),
                                            'type': 'VBComboBox'},
                                           {'items': ['simple', 'combo'],
                                            'name': 'Combo2',
                                            'position': (16, 32),
                                            'size': (201, 21),
                                            'type': 'VBComboBox'},
                                           {'backgroundColor': (0,
                                                                192,
                                                                0),
                                            'foregroundColor': (192,
                                                                0,
                                                                0),
                                            'items': ['editable',
                                                      'combo'],
                                            'name': 'Combo3',
                                            'position': (232, 32),
                                            'size': (201, 29),
                                            'type': 'VBComboBox'},
                                           {'items': ['dropdown', 'list'],
                                            'name': 'Combo4',
                                            'position': (16, 80),
                                            'size': (201, 21),
                                            'type': 'VBComboBox'},
                                           {'label': 'Make Visible',
                                            'name': 'Command4',
                                            'position': (472, 32),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Move ',
                                            'name': 'Command5',
                                            'position': (568, 32),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Size ',
                                            'name': 'Command6',
                                            'position': (664, 32),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Enable',
                                            'name': 'Command7',
                                            'position': (760, 32),
                                            'size': (97, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Delete',
                                            'name': 'Delete',
                                            'position': (712, 96),
                                            'size': (81, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Add',
                                            'name': 'cmdAdd',
                                            'position': (632, 96),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Add as first',
                                            'name': 'cmdAddFirst',
                                            'position': (544, 96),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Clear',
                                            'name': 'cmdClear',
                                            'position': (800, 96),
                                            'size': (57, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Dump out',
                                            'name': 'cmdDump',
                                            'position': (464, 96),
                                            'size': (73, 25),
                                            'type': 'VBButton'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmComboBox',
                            'position': (4, 30),
                            'size': (900, 494),
                            'style': ['resizeable'],
                            'title': 'ComboBox',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
