{'stack': {'backgrounds': [{'components': [{'label': 'Remove directory',
                                            'name': 'Command1',
                                            'position': (408, 72),
                                            'size': (105, 25),
                                            'type': 'VBButton'},
                                           {'label': 'CheckTest file',
                                            'name': 'cmdCheck',
                                            'position': (256, 104),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Delete Test file',
                                            'name': 'cmdDelete',
                                            'position': (256, 72),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'List Files',
                                            'name': 'cmdListFiles',
                                            'position': (168, 312),
                                            'size': (81, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Make directory',
                                            'name': 'cmdMakeDir',
                                            'position': (408, 40),
                                            'size': (105, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Make Test file',
                                            'name': 'cmdMakeTestFile',
                                            'position': (256, 40),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Set',
                                            'name': 'cmdSet',
                                            'position': (464, 8),
                                            'size': (49, 25),
                                            'type': 'VBButton'},
                                           {'items': [],
                                            'name': 'lstFiles',
                                            'position': (16, 40),
                                            'size': (233, 264),
                                            'type': 'VBList'},
                                           {'name': 'txtDir',
                                            'position': (16, 8),
                                            'size': (441, 25),
                                            'text': 'c:\temp',
                                            'type': 'VBTextField'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmFiles',
                            'position': (4, 30),
                            'size': (521, 380),
                            'style': ['resizeable'],
                            'title': 'File Testing',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
