{'stack': {'backgrounds': [{'components': [{'label': 'Set Strech',
                                            'name': 'Command1',
                                            'position': (248, 48),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Load New',
                                            'name': 'Command2',
                                            'position': (248, 88),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Make Visible',
                                            'name': 'Command4',
                                            'position': (248, 16),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Move ',
                                            'name': 'Command5',
                                            'position': (344, 16),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Size ',
                                            'name': 'Command6',
                                            'position': (440, 16),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Enable',
                                            'name': 'Command7',
                                            'position': (536, 16),
                                            'size': (97, 25),
                                            'type': 'VBButton'},
                                           {'Stretch': 0,
                                            'name': 'Image1',
                                            'position': (16, 16),
                                            'size': (158, 92),
                                            'type': 'VBBitmapCanvas'},
                                           {'name': 'Label1',
                                            'position': (344, 56),
                                            'text': 'Label1',
                                            'type': 'VBStaticText'},
                                           {'name': 'Label2',
                                            'position': (344, 96),
                                            'text': 'Label2',
                                            'type': 'VBStaticText'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmImage',
                            'position': (4, 30),
                            'size': (770, 271),
                            'style': ['resizeable'],
                            'title': 'Image',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
