{'stack': {'backgrounds': [{'components': [{'label': 'Make Visible',
                                            'name': 'Command4',
                                            'position': (480, 16),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Move ',
                                            'name': 'Command5',
                                            'position': (576, 16),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Size ',
                                            'name': 'Command6',
                                            'position': (672, 16),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Enable',
                                            'name': 'Command7',
                                            'position': (768, 16),
                                            'size': (97, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Delete',
                                            'name': 'Delete',
                                            'position': (272, 144),
                                            'size': (81, 25),
                                            'type': 'VBButton'},
                                           {'items': [],
                                            'name': 'List1',
                                            'position': (16, 16),
                                            'size': (401, 121),
                                            'type': 'VBList'},
                                           {'items': [],
                                            'name': 'List2',
                                            'position': (480, 48),
                                            'size': (385, 108),
                                            'type': 'VBList'},
                                           {'label': 'Add',
                                            'name': 'cmdAdd',
                                            'position': (192, 144),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Add as first',
                                            'name': 'cmdAddFirst',
                                            'position': (104, 144),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Clear',
                                            'name': 'cmdClear',
                                            'position': (360, 144),
                                            'size': (57, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Dump out',
                                            'name': 'cmdDump',
                                            'position': (24, 144),
                                            'size': (73, 25),
                                            'type': 'VBButton'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmListBox',
                            'position': (4, 30),
                            'size': (964, 438),
                            'style': ['resizeable'],
                            'title': 'Form1',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
