{'stack': {'backgrounds': [{'components': [{'label': 'Button',
                                            'name': 'Command1',
                                            'position': (16, 16),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Settings',
                                            'name': 'Command10',
                                            'position': (200, 104),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Erase Test',
                                            'name': 'Command11',
                                            'position': (296, 104),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'TextBox',
                                            'name': 'Command2',
                                            'position': (104, 16),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'ComboBox',
                                            'name': 'Command3',
                                            'position': (200, 16),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'ListBox',
                                            'name': 'Command4',
                                            'position': (296, 16),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Check',
                                            'name': 'Command5',
                                            'position': (16, 64),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Image',
                                            'name': 'Command6',
                                            'position': (104, 64),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Test',
                                            'name': 'Command7',
                                            'position': (16, 104),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Files',
                                            'name': 'Command8',
                                            'position': (104, 104),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Random',
                                            'name': 'Command9',
                                            'position': (200, 64),
                                            'size': (73, 25),
                                            'type': 'VBButton'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmMain',
                            'position': (4, 30),
                            'size': (499, 469),
                            'style': ['resizeable'],
                            'title': 'Main Navigation Form',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
