{'stack': {'backgrounds': [{'components': [{'name': 'Label1',
                                            'position': (16, 8),
                                            'text': 'Seed',
                                            'type': 'VBStaticText'},
                                           {'label': 'Get Random',
                                            'name': 'cmdGetRandom',
                                            'position': (296, 304),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Call rnd with -ve',
                                            'name': 'cmdNegCall',
                                            'position': (192, 304),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Randomize no seed',
                                            'name': 'cmdRandomize',
                                            'position': (184, 40),
                                            'size': (113, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Randomize with seed',
                                            'name': 'cmdRandomizeWithSeed',
                                            'position': (184, 8),
                                            'size': (113, 25),
                                            'type': 'VBButton'},
                                           {'name': 'txtResults',
                                            'position': (16, 80),
                                            'size': (369, 217),
                                            'text': 'Text',
                                            'type': 'VBTextArea'},
                                           {'name': 'txtSeed',
                                            'position': (72, 8),
                                            'size': (97, 25),
                                            'text': '1234',
                                            'type': 'VBTextField'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmRandom',
                            'position': (4, 30),
                            'size': (414, 364),
                            'style': ['resizeable'],
                            'title': 'Random',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
