{'stack': {'backgrounds': [{'components': [{'label': 'Delete',
                                            'name': 'cmdDelete',
                                            'position': (232, 80),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Get',
                                            'name': 'cmdGet',
                                            'position': (232, 16),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Get All',
                                            'name': 'cmdGetAll',
                                            'position': (232, 240),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Set',
                                            'name': 'cmdSet',
                                            'position': (232, 48),
                                            'size': (73, 25),
                                            'type': 'VBButton'},
                                           {'items': [],
                                            'name': 'lstSettings',
                                            'position': (24, 64),
                                            'size': (193, 199),
                                            'type': 'VBList'},
                                           {'name': 'txtName',
                                            'position': (136, 16),
                                            'size': (81, 25),
                                            'text': 'MySetting',
                                            'type': 'VBTextField'},
                                           {'name': 'txtSection',
                                            'position': (24, 16),
                                            'size': (105, 25),
                                            'text': 'Main',
                                            'type': 'VBTextField'},
                                           {'name': 'txtValue',
                                            'position': (320, 16),
                                            'size': (81, 25),
                                            'text': '',
                                            'type': 'VBTextField'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmSettings',
                            'position': (4, 30),
                            'size': (468, 346),
                            'style': ['resizeable'],
                            'title': 'Settings',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
