{'stack': {'backgrounds': [{'components': [{'label': 'Make Visible',
                                            'name': 'Command4',
                                            'position': (472, 8),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Move ',
                                            'name': 'Command5',
                                            'position': (568, 8),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Size ',
                                            'name': 'Command6',
                                            'position': (664, 8),
                                            'size': (89, 25),
                                            'type': 'VBButton'},
                                           {'label': 'Enable',
                                            'name': 'Command7',
                                            'position': (760, 8),
                                            'size': (97, 25),
                                            'type': 'VBButton'},
                                           {'name': 'Text1',
                                            'position': (8, 8),
                                            'size': (209, 25),
                                            'text': 'Single',
                                            'type': 'VBTextField'},
                                           {'backgroundColor': (0,
                                                                128,
                                                                255),
                                            'foregroundColor': (255,
                                                                0,
                                                                0),
                                            'name': 'Text2',
                                            'position': (232, 8),
                                            'size': (209, 25),
                                            'text': 'Coloured',
                                            'type': 'VBTextField'},
                                           {'name': 'Text3',
                                            'position': (472, 40),
                                            'size': (385, 25),
                                            'text': 'Movable one',
                                            'type': 'VBTextField'},
                                           {'name': 'Text4',
                                            'position': (8, 40),
                                            'size': (209, 153),
                                            'text': 'Multiple line',
                                            'type': 'VBTextArea'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmTextBox',
                            'position': (4, 30),
                            'size': (953, 352),
                            'style': ['resizeable'],
                            'title': 'TextBox',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
