{'stack': {'backgrounds': [{'components': [{'name': 'Frame1',
                                            'position': (16, 440),
                                            'size': (369, 121),
                                            'type': 'StaticBox'},
                                           {'label': 'Load pictures',
                                            'name': 'cmdLoadPicture',
                                            'position': (40, 464),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Set as dynamic',
                                            'name': 'cmdSetAsDynamic',
                                            'position': (152, 512),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Set as preload',
                                            'name': 'cmdSetAsPreload',
                                            'position': (40, 512),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Set pictures',
                                            'name': 'cmdSetPictures',
                                            'position': (152, 464),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'name': 'Frame2',
                                            'position': (456, 8),
                                            'size': (193, 185),
                                            'type': 'StaticBox'},
                                           {'label': 'Test',
                                            'name': 'cmdTestNode',
                                            'position': (472, 32),
                                            'size': (57, 33),
                                            'type': 'VBButton'},
                                           {'name': 'txtNodeName',
                                            'position': (536, 40),
                                            'size': (97, 25),
                                            'text': 'A2',
                                            'type': 'VBTextField'},
                                           {'name': 'txtResults',
                                            'position': (472, 80),
                                            'size': (161, 97),
                                            'text': 'Results\n',
                                            'type': 'VBTextArea'},
                                           {'checked': 1,
                                            'label': 'Allow label edits',
                                            'name': 'chkAllowEdits',
                                            'position': (456, 248),
                                            'type': 'VBCheckBox'},
                                           {'checked': 1,
                                            'label': 'Enable auto edit',
                                            'name': 'chkEnableAutoEdit',
                                            'position': (456, 272),
                                            'type': 'VBCheckBox'},
                                           {'label': 'Add',
                                            'name': 'cmdAdd',
                                            'position': (336, 200),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Add Tree',
                                            'name': 'cmdAddTree',
                                            'position': (336, 328),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Clear',
                                            'name': 'cmdClear',
                                            'position': (336, 280),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Collapse All',
                                            'name': 'cmdCollapse',
                                            'position': (176, 400),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Enable',
                                            'name': 'cmdEnable',
                                            'position': (336, 48),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Expand All',
                                            'name': 'cmdExpand',
                                            'position': (64, 400),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Move',
                                            'name': 'cmdMove',
                                            'position': (336, 88),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Remove',
                                            'name': 'cmdRemove',
                                            'position': (336, 240),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Size',
                                            'name': 'cmdSize',
                                            'position': (336, 128),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'label': 'Visible',
                                            'name': 'cmdVisible',
                                            'position': (336, 8),
                                            'size': (105, 33),
                                            'type': 'VBButton'},
                                           {'backgroundColor': 'Grey',
                                            'name': 'ilDynamic',
                                            'position': (400, 440),
                                            'type': 'VBImageList'},
                                           {'backgroundColor': 'Grey',
                                            'name': 'imPreload',
                                            'position': (400, 488),
                                            'type': 'VBImageList'},
                                           {'name': 'tvTree',
                                            'position': (8, 8),
                                            'size': (313, 377),
                                            'type': 'VBTreeView'},
                                           {'name': 'txtName',
                                            'position': (448, 208),
                                            'size': (161, 25),
                                            'text': 'Next node',
                                            'type': 'VBTextField'},
                                           {'name': 'txtTree',
                                            'position': (456, 328),
                                            'size': (193, 153),
                                            'text': 'Hello\n',
                                            'type': 'VBTextArea'}],
                            'menubar': {'menus': [], 'type': 'MenuBar'},
                            'name': 'frmMain',
                            'position': (4, 30),
                            'size': (665, 596),
                            'style': ['resizeable'],
                            'title': 'Tree view test form',
                            'type': 'Background'}],
           'name': 'Template',
           'type': 'Stack'}}
