#@+leo-ver=4-thin
#@+node:pap.20070203004134:@thin vb2pyGUI.rsrc.py
{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'vb2pyGUI',
          'title':'vb2Py : VB to Python Conversion Toolkit',
          'position':(340, 102),
          'size':(608, 637),
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileOpen',
                   'label':'&Open\tCtrl+O',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSave',
                   'label':'&Save\tCtrl+S',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit\tCtrl+X',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuEdit',
             'label':'Edit',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFind',
                   'label':'Find\tCtrl+F',
                  },
                  {'type':'MenuItem',
                   'name':'menuFindNext',
                   'label':'Find next\tF3',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuView',
             'label':'View',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuOptions',
                   'label':'Options ...',
                  },
                  {'type':'MenuItem',
                   'name':'menuViewStructure',
                   'label':'View Structure',
                  },
                  {'type':'MenuItem',
                   'name':'menuTestView',
                   'label':'Testing Window',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuConversion',
             'label':'Convert',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuConvert',
                   'label':'Convert active\tCtrl+A',
                  },
                  {'type':'MenuItem',
                   'name':'menuConvertSelection',
                   'label':'Convert selection\tCtrl+Shift+S',
                  },
                  {'type':'MenuItem',
                   'name':'menuSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuCodeModuleContext',
                   'label':'Code Module',
                   'checkable':1,
                   'checked':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuClassModuleContext',
                   'label':'Class Module',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuFormModuleContext',
                   'label':'Form Module',
                   'checkable':1,
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':'Help',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuHelp',
                   'label':'vb2Py Help\tF1',
                  },
                  {'type':'MenuItem',
                   'name':'menuHelpGUI',
                   'label':'GUI Help',
                  },
                  {'type':'MenuItem',
                   'name':'menuSep2',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuAbout',
                   'label':'About vb2Py',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'StaticText', 
    'name':'txtStatus', 
    'position':(3, 560), 
    'size':(191, 16), 
    'text':'Loading file ...', 
    'visible':0, 
    },

{'type':'Gauge', 
    'name':'prgProgress', 
    'position':(199, 558), 
    'size':(394, 19), 
    'layout':'horizontal', 
    'max':100, 
    'value':0, 
    'visible':0, 
    },

{'type':'TextArea', 
    'name':'logWindow', 
    'position':(0, 455), 
    'size':(595, 100), 
    'alignment':'left', 
    'backgroundColor':(204, 204, 255), 
    'editable':0, 
    },

{'type':'TextArea', 
    'name':'vbText', 
    'position':(270, 0), 
    'size':(325, 181), 
    'alignment':'left', 
    'font':{'faceName': 'Courier New', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'CodeEditor', 
    'name':'pythonText', 
    'position':(269, 186), 
    'size':(325, 270), 
    'backgroundColor':(255, 255, 255), 
    },

{'type':'Tree', 
    'name':'parseTree', 
    'position':(0, 0), 
    'size':(264, 455), 
    'backgroundColor':(255, 255, 255), 
    'command':'treeClick', 
    },

] # end components
} # end background
] # end backgrounds
} }
#@-node:pap.20070203004134:@thin vb2pyGUI.rsrc.py
#@-leo
