{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'Wizard',
          'title':'vb2Py : Conversion',
          'size':(608, 637),
          'backgroundColor':(255, 255, 255),
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileOpen',
                   'label':'&Open\tCtrl+O',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSave',
                   'label':'&Save\tCtrl+S',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit\tCtrl+X',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuEdit',
             'label':'Edit',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFind',
                   'label':'Find\tCtrl+F',
                  },
                  {'type':'MenuItem',
                   'name':'menuFindNext',
                   'label':'Find next\tF3',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuView',
             'label':'View',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuOptions',
                   'label':'Options ...',
                  },
                  {'type':'MenuItem',
                   'name':'menuViewStructure',
                   'label':'View Structure',
                  },
                  {'type':'MenuItem',
                   'name':'menuTestView',
                   'label':'Testing Window',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuConversion',
             'label':'Convert',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuConvert',
                   'label':'Convert active\tCtrl+A',
                  },
                  {'type':'MenuItem',
                   'name':'menuConvertSelection',
                   'label':'Convert selection\tCtrl+Shift+S',
                  },
                  {'type':'MenuItem',
                   'name':'menuSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuCodeModuleContext',
                   'label':'Code Module',
                   'checkable':1,
                   'checked':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuClassModuleContext',
                   'label':'Class Module',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuFormModuleContext',
                   'label':'Form Module',
                   'checkable':1,
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':'Help',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuHelp',
                   'label':'vb2Py Help\tF1',
                  },
                  {'type':'MenuItem',
                   'name':'menuHelpGUI',
                   'label':'GUI Help',
                  },
                  {'type':'MenuItem',
                   'name':'menuSep2',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuAbout',
                   'label':'About vb2Py',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Button', 
    'name':'GoInteractive', 
    'position':(231, 108), 
    'label':'Convert code snippets interactively', 
    },

{'type':'Image', 
    'name':'Image3', 
    'position':(80, 381), 
    'file':'images/project.jpg', 
    },

{'type':'Image', 
    'name':'Image2', 
    'position':(86, 214), 
    'file':'images/file.jpg', 
    },

{'type':'Image', 
    'name':'Image1', 
    'position':(91, 69), 
    'file':'images/interactive.jpg', 
    },

] # end components
} # end background
] # end backgrounds
} }
